fix(ci): Split tf-ci into needing/not needing AWS access

diff --git a/.github/actions/tf-ci-aws/action.yaml b/.github/actions/tf-ci-aws/action.yaml
--- a/.github/actions/tf-ci-aws/action.yaml
+++ b/.github/actions/tf-ci-aws/action.yaml
@@ -1,12 +1,12 @@
-name: Terragrunt CI
-description: Run TG checks
+name: OpenTofu CI AWS
+description: Run TF checks that require AWS access
 
 inputs:
   component-type:
-    description: "Type of component to run CI on, eg: `env`"
+    description: "Type of component to run CI on, eg: `feature`"
     required: true
   component-name:
-    description: "Name of the component to run CI on, eg: `dev`"
+    description: "Name of the component to run CI on, eg: `networking`"
     required: true
   role-arn:
     description: "ARN of the role to assume"
@@ -18,13 +18,12 @@ inputs:
 runs:
   using: composite
   steps:
-  - name: Install OpenTofu and Terragrunt
-    uses: gruntwork-io/terragrunt-action@v3
+  - name: Install OpenTofu
+    uses: opentofu/setup-opentofu@v1
 
-  - name: Print Terragrunt and OpenTofu versions
+  - name: Print OpenTofu version
     shell: bash
     run: |
-      echo "Terragrunt version: $(terragrunt version)"
       echo "OpenTofu version: $(tofu version)"
 
   - name: Ensure TF cache folder exists
@@ -45,7 +44,7 @@ runs:
     env:
       AWS_REGION: ${{ inputs.aws-region }}
     run: |
-      creds=$(aws sts assume-role --role-arn "${{ inputs.role-arn }}" --role-session-name tg-ci)
+      creds=$(aws sts assume-role --role-arn "${{ inputs.role-arn }}" --role-session-name tf-ci-aws)
       echo "AWS_ACCESS_KEY_ID=$(echo "$creds" | jq -r '.Credentials.AccessKeyId')" >> $GITHUB_ENV
       echo "AWS_SECRET_ACCESS_KEY=$(echo "$creds" | jq -r '.Credentials.SecretAccessKey')" >> $GITHUB_ENV
       echo "AWS_SESSION_TOKEN=$(echo "$creds" | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV
@@ -54,27 +53,26 @@ runs:
   - name: Run CI job
     shell: bash
     env:
-      TF_PLUGIN_CACHE_DIR: /tmp/tf-cache
       AWS_REGION: ${{ inputs.aws-region }}
+      TF_PLUGIN_CACHE_DIR: /tmp/tf-cache
     run: |
       make ci-${{ inputs.component-type }}-${{ inputs.component-name }} CHECKOV=0
 
-  # It seems Checkov doesn't do anything on Terragrunt stacks...
-  # - name: Run Checkov
-  #   uses: bridgecrewio/checkov-action@v12
-  #   with:
-  #     directory: ./${{ inputs.component-type }}/${{ inputs.component-name }}
-  #     quiet: true
-  #     output_format: cli,sarif
-  #     output_file_path: console,results.sarif
+  - name: Run Checkov
+    uses: bridgecrewio/checkov-action@v12
+    with:
+      directory: ./${{ inputs.component-type }}/${{ inputs.component-name }}
+      quiet: true
+      output_format: cli,sarif
+      output_file_path: console,results.sarif
 
-  # - name: Upload Checkov SARIF file
-  #   uses: github/codeql-action/upload-sarif@v4
-  #   # Results are generated only on a success or failure
-  #   # this is required since GitHub by default won't run the next step
-  #   # when the previous one has failed. Security checks that do not pass will 'fail'.
-  #   # An alternative is to add `continue-on-error: true` to the previous step
-  #   # Or 'soft_fail: true' to checkov.
-  #   if: success() || failure()
-  #   with:
-  #     sarif_file: results.sarif
+  - name: Upload Checkov SARIF file
+    uses: github/codeql-action/upload-sarif@v4
+    # Results are generated only on a success or failure
+    # this is required since GitHub by default won't run the next step
+    # when the previous one has failed. Security checks that do not pass will 'fail'.
+    # An alternative is to add `continue-on-error: true` to the previous step
+    # Or 'soft_fail: true' to checkov.
+    if: success() || failure()
+    with:
+      sarif_file: results.sarif
