feat(features): Turn the networking feature into a Terragrunt unit (#31)

diff --git a/.github/workflows/bootstrap-all-ci.yaml b/.github/workflows/bootstrap-all-ci.yaml
--- a/.github/workflows/bootstrap-all-ci.yaml
+++ b/.github/workflows/bootstrap-all-ci.yaml
@@ -11,22 +11,78 @@ on:
     paths:
     - bootstrap/all/**
     - .github/workflows/bootstrap-all-ci.yaml
-    - .github/actions/tg-ci/**
+    - .github/actions/tf-ci/**
     - Makefile
 
+permissions:
+  id-token: write         # This is required for requesting the JWT
+  contents: read          # This is required for actions/checkout
+  security-events: write  # For `github/codeql-action/upload-sarif` to upload SARIF results
+
+# NB: Bootstrap is a special case so we don't use the actions defined in this
+# repo, we just write our custom steps.
 jobs:
   ci:
-    permissions:
-      contents: read
-      security-events: write  # For `github/codeql-action/upload-sarif` to upload SARIF results
     runs-on: ubuntu-latest
+    environment: bootstrap
 
     steps:
     - name: Checkout the code
       uses: actions/checkout@v5
 
-    - name: Run CI
-      uses: ./.github/actions/tg-ci
+    # NB: Running `make ci-bootstrap-all` requires AWS access to the management account
+    - name: Configure AWS credentials
+      uses: aws-actions/configure-aws-credentials@v6
       with:
-        component-type: bootstrap
-        component-name: all
+        role-to-assume: arn:aws:iam::${{ vars.AWS_MANAGEMENT_ACCOUNT_ID }}:role/github-actions-role
+        role-session-name: github-actions
+        aws-region: ${{ vars.AWS_REGION }}
+
+    - name: Install OpenTofu and Terragrunt
+      uses: gruntwork-io/terragrunt-action@v3
+
+    - name: Print Terragrunt and OpenTofu versions
+      shell: bash
+      run: |
+        echo "Terragrunt version: $(terragrunt version)"
+        echo "OpenTofu version: $(tofu version)"
+
+    - name: Ensure TF cache folder exists
+      shell: bash
+      run: mkdir -p /tmp/tf-cache
+
+    - name: Restore or create the TF cache
+      uses: actions/cache@v4
+      with:
+        path: /tmp/tf-cache
+        key: ${{ runner.os }}-tf-bootstrap-all
+        restore-keys: |
+          ${{ runner.os }}-tf-bootstrap-all
+          ${{ runner.os }}-tf-
+
+    - name: Run CI job
+      shell: bash
+      env:
+        TF_PLUGIN_CACHE_DIR: /tmp/tf-cache
+        AWS_REGION: ${{ vars.AWS_REGION }}
+      run: |
+        make ci-bootstrap-all CHECKOV=0
+
+    - name: Run Checkov
+      uses: bridgecrewio/checkov-action@v12
+      with:
+        directory: ./bootstrap/all
+        quiet: true
+        output_format: cli,sarif
+        output_file_path: console,results.sarif
+
+    - name: Upload Checkov SARIF file
+      uses: github/codeql-action/upload-sarif@v4
+      # Results are generated only on a success or failure
+      # this is required since GitHub by default won't run the next step
+      # when the previous one has failed. Security checks that do not pass will 'fail'.
+      # An alternative is to add `continue-on-error: true` to the previous step
+      # Or 'soft_fail: true' to checkov.
+      if: success() || failure()
+      with:
+        sarif_file: results.sarif
