feat(ci): Fix a few bugs

diff --git a/.github/workflows/delete-container-image.yaml b/.github/workflows/delete-container-image.yaml
--- a/.github/workflows/delete-container-image.yaml
+++ b/.github/workflows/delete-container-image.yaml
@@ -1,4 +1,4 @@
-# Delete a container image from either the nonprod orprod ECR registry
+# Delete a container image from either the nonprod or prod ECR registry
 name: ++ Delete container image
 
 on:
@@ -50,7 +50,7 @@ jobs:
         AWS_REGION: ${{ vars.AWS_REGION }}
       run: |
         trap 'echo "FAILURE_REASON=Failed to assume role in child account" >> "$GITHUB_ENV" && exit 1' ERR
-        creds=$(aws sts assume-role --role-arn "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/tf-role-${{ vars.AWS_REGION }}" --role-session-name import-image)
+        creds=$(aws sts assume-role --role-arn "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/tf-role-${{ vars.AWS_REGION }}" --role-session-name delete-image)
         echo "AWS_ACCESS_KEY_ID=$(echo "$creds" | jq -r '.Credentials.AccessKeyId')" >> "$GITHUB_ENV"
         echo "AWS_SECRET_ACCESS_KEY=$(echo "$creds" | jq -r '.Credentials.SecretAccessKey')" >> "$GITHUB_ENV"
         echo "AWS_SESSION_TOKEN=$(echo "$creds" | jq -r '.Credentials.SessionToken')" >> "$GITHUB_ENV"
@@ -71,11 +71,21 @@ jobs:
         fi
         name="${IMAGE%%:*}"
         tag="${IMAGE##*:}"
-        if ! aws ecr batch-delete-image --repository-name "$name" --image-ids imageTag="$tag"; then
+        response=$(aws ecr batch-delete-image --repository-name "$name" --image-ids imageTag="$tag")
+        if [ $? -ne 0 ]; then
           echo "Failed to delete image from $ENV ECR"
           echo "FAILURE_REASON=Failed to delete image from $ENV ECR" >> "$GITHUB_ENV"
           exit 1
         fi
+        if [ "$(echo "$response" | jq -r '.failures | length')" -ne 0 ]; then
+          reason=$(echo "$response" | jq -r '.failures[0].failureCode')
+          echo "Failed to delete image from $ENV ECR: $reason"
+          echo "FAILURE_REASON=Failed to delete image from $ENV ECR: $reason" >> "$GITHUB_ENV"
+          exit 1
+        fi
+        digest=$(echo "$response" | jq -r '.imageIds[0].imageDigest')
+        echo "DIGEST=$digest"
+        echo "DIGEST=$digest" >> "$GITHUB_ENV"
 
     - name: Audit trail
       if: success() || failure()
@@ -97,11 +107,12 @@ jobs:
         actor_id="$GITHUB_ACTOR_ID"
         utc_now=$(date -u +%Y%m%dT%H%M%S)
         image="$IMAGE"
+        digest="$DIGEST"
         account_id="$ACCOUNT_ID"
         region="$AWS_REGION"
         if [[ -z "${FAILURE_REASON:-}" ]]; then
           success=true
-          reason=""
+          reason="Image successfully deleted"
         else
           success=false
           reason="$FAILURE_REASON"
@@ -114,6 +125,7 @@ jobs:
           --arg actor_id "$actor_id" \
           --arg utc_now "$utc_now" \
           --arg image "$image" \
+          --arg digest "$digest" \
           --arg account_id "$account_id" \
           --arg region "$region" \
           --arg github_run_id "$run_id" \
@@ -125,6 +137,7 @@ jobs:
             actor_id: $actor_id,
             utc_now: $utc_now,
             image: $image,
+            digest: $digest,
             account_id: $account_id,
             region: $region,
             github_run_id: $github_run_id,
